### ISSUE TITLE
[Bug] Page Crashes When Starting Test Run for Unfinished Qog

### ISSUE THREAD

**Issue by nickmazurenko** [qoretechnologies/qorus-ide#31]
### Issue Summary
When starting a test run for an unfinished Qog, the page crashes unexpectedly. This issue occurs when the user initiates a test run without completing the Qog.

---

### Steps to Reproduce
- Create a new Qog.
- Add any action.
- Press the Test button.

---

### Expected Behavior
The system should display an appropriate error message indicating that the Qog is unfinished instead of crashing the page.

---

### Actual Behavior
The page crashes when the Test button is pressed for an unfinished Qog, without providing an error message.

---

### Additional

# Error
```
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at renderContent (http://localhost:3005/static/js/bundle.js:28696:33)
    at QodexTestRunModal (http://localhost:3005/static/js/bundle.js:28765:15)
    at renderWithHooks (http://localhost:3005/static/js/bundle.js:288735:22)
    at updateFunctionComponent (http://localhost:3005/static/js/bundle.js:291935:24)
    at beginWork (http://localhost:3005/static/js/bundle.js:293882:20)
    at beginWork$1 (http://localhost:3005/static/js/bundle.js:299630:18)
    at performUnitOfWork (http://localhost:3005/static/js/bundle.js:298788:16)
    at workLoopSync (http://localhost:3005/static/js/bundle.js:298701:9)
    at renderRootSync (http://localhost:3005/static/js/bundle.js:298670:11)
```

**Comment by davidnich** [comment]
should be fixed in all cases now as validations are done on the server side
