### ISSUE TITLE
[Bug] Page Crash on Dynamic Option Loading for Notion "Create Database Item" Action

### ISSUE THREAD

**Issue by nickmazurenko** [qoretechnologies/qorus-ide#33]
### Issue Summary
Action with dynamic options crashes the page when loading options. This issue occurs when the user tries to dynamically populate fields for Notion actions in a Qog, leading to a page crash.

---

### Steps to Reproduce
- Create a new Qog.
- Add a "Create Database" action from Notion.
- Create a database using default values.
- Add another Notion action - "Create Database Item."
- Input the databaseId.

---

### Expected Behavior
The system should display dynamic options to fill out for item creation based on the selected `databaseId` without crashing the page.

---

### Actual Behavior
The page crashes when attempting to load the dynamic options for item creation after providing the databaseId.

---

#### Error
```
Error: Objects are not valid as a React child (found: object with keys {type, children}). If you meant to render a collection of children, use an array instead.
    at throwOnInvalidObjectType (http://localhost:3005/static/js/bundle.js:287331:13)
    at createChild (http://localhost:3005/static/js/bundle.js:287580:11)
    at reconcileChildrenArray (http://localhost:3005/static/js/bundle.js:287839:29)
    at reconcileChildFibers (http://localhost:3005/static/js/bundle.js:288251:20)
    at reconcileChildren (http://localhost:3005/static/js/bundle.js:291537:32)
    at updateHostComponent (http://localhost:3005/static/js/bundle.js:292261:7)
    at beginWork (http://localhost:3005/static/js/bundle.js:293899:18)
    at beginWork$1 (http://localhost:3005/static/js/bundle.js:299630:18)
    at performUnitOfWork (http://localhost:3005/static/js/bundle.js:298788:16)
    at workLoopSync (http://localhost:3005/static/js/bundle.js:298701:9)
```

#### Response from the options request

```
{
    "options": {
        "qorus_app_connection": {
            "app": "Notion",
            "action": "create_database_item",
            "on_change": [
                "refetch"
            ],
            "metadata": {
                "oauth2_auth_code": true
            },
            "type": "connection",
            "display_name": "Connection to Notion",
            "short_desc": "Connection to Notion",
            "desc": "The connection to the Notion server supporting the action",
            "required": true,
            "allowed_values": [
                {
                    "short_desc": "Connection to \"Notion\"",
                    "value": "tsrest-notion-1",
                    "desc": "Connection to \"Notion\"",
                    "display_name": "Notion Connection 1",
                    "metadata": {
                        "oauth2_auth_code": true
                    }
                },
                {
                    "short_desc": "Connection to \"Notion\"",
                    "value": "tsrest-notion",
                    "desc": "Connection to \"Notion\"",
                    "display_name": "Notion Connection",
                    "metadata": {
                        "oauth2_auth_code": true,
                        "needs_auth": true
                    },
                    "intent": "warning"
                }
            ],
            "disallow_template": true,
            "has_dependents": true,
            "supports_templates": true,
            "supports_expressions": true,
            "sort": 1
        },
        "database_id": {
            "type": "richtext",
            "desc": "Select the database you want to use",
            "value": "129ba26f-2e25-8198-8a16-c44f1daf100e",
            "display_name": "Database",
            "short_desc": "Select the database you want to use",
            "required": true,
            "default_value": null,
            "preselected": true,
            "depends_on": [
                "qorus_app_connection"
            ],
            "allowed_values": [
                {
                    "display_name": "Testing Database",
                    "short_desc": "Testing Database",
                    "value": "129ba26f-2e25-8198-8a16-c44f1daf100e",
                    "desc": "Testing Database"
                },
                {
                    "display_name": "Meetings",
                    "short_desc": "Meetings",
                    "value": "105ba26f-2e25-808c-9640-c7eeeb39008c",
                    "desc": "Meetings"
                },
                {
                    "display_name": "Tasks",
                    "short_desc": "Tasks",
                    "value": "105ba26f-2e25-80ed-8f60-cdb2e63e740f",
                    "desc": "Tasks"
                },
                {
                    "display_name": "Docs",
                    "short_desc": "Docs",
                    "value": "e0058efe-1840-465a-bfbc-e930f32f7b11",
                    "desc": "Docs"
                }
            ],
            "app": "Notion",
            "action": "create_database_item",
            "supports_templates": true,
            "supports_expressions": true,
            "sort": 2
        },
        "content": {
            "type": "richtext",
            "desc": "The content you want to append to your item.",
            "value": "test",
            "display_name": "Content",
            "short_desc": "The content you want to append to your item.",
            "required": false,
            "default_value": null,
            "app": "Notion",
            "action": "create_database_item",
            "supports_templates": true,
            "supports_expressions": true,
            "sort": 3
        },
        "Last ordered": {
            "type": "date",
            "desc": "Last ordered",
            "display_name": "Last ordered",
            "short_desc": "Last ordered",
            "default_value": null,
            "app": "Notion",
            "action": "create_database_item",
            "supports_templates": true,
            "supports_expressions": true,
            "sort": 4
        },
        "Price": {
            "type": "number",
            "desc": "Price",
            "display_name": "Price",
            "short_desc": "Price",
            "default_value": null,
            "app": "Notion",
            "action": "create_database_item",
            "supports_templates": true,
            "supports_expressions": true,
            "sort": 5
        },
        "Grocery item": {
            "type": "richtext",
            "desc": "Grocery item",
            "display_name": "Grocery item",
            "short_desc": "Grocery item",
            "default_value": null,
            "app": "Notion",
            "action": "create_database_item",
            "supports_templates": true,
            "supports_expressions": true,
            "sort": 6
        }
    }
}
```

**Comment by davidnich** [comment]
this works but the API call fails due to a JS error
