### ISSUE TITLE
input lag on Qogs can result in publishing incorrect info

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-ide#42]
ex: create a new Qog
type in the last value of a string option, for example, and hit `Publish` immediately - ex: I typed `ondewo-bpi` in a text field and hit public, and the Qog failed with the following error after publishing:
```
2024-12-09 17:33:09.470698 hq.qoretechnologies.com:1367976 T660 [ERROR]: User exception: /export/home2/dnichols/src/Qorus/current/qlib/TypeScriptActionInterface/TypeScriptActionDataProviderBase.qc:286 (Qore): JAVASCRIPT-ASYNC-ERROR: Error in async request (promise rejected) detail: INTERNAL-ERROR: {"message":"Not Found","documentation_url":"https://docs.github.com/rest/repos/webhooks#create-a-repository-webhook","status":"404"}
    at new BaseError (/export/home2/dnichols/src/qore/git/module-v8/ts/node_modules/@qoretechnologies/ts-toolkit/dist/managers/error/Error.js:12:80)
    at new ErrorQorusRequest (/export/home2/dnichols/src/qore/git/module-v8/ts/node_modules/@qoretechnologies/ts-toolkit/dist/managers/error/ErrorQorusRequest.js:11:13)
    at QorusRequest.makeRequest (/export/home2/dnichols/src/qore/git/module-v8/ts/node_modules/@qoretechnologies/ts-toolkit/dist/QorusRequest.js:56:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async QorusRequest.post (/export/home2/dnichols/src/qore/git/module-v8/ts/node_modules/@qoretechnologies/ts-toolkit/dist/QorusRequest.js:79:24)
    at async AsyncFunction.webhook_register (/export/home2/dnichols/src/qore/git/module-v8/ts/dist/apps/github/triggers/new-issue.trigger.js:22:26) (context: Webhook registration function for app "Github" action "new_repository_issue") (while registering webhook URL "https://hq.qoretechnologies.com:8092/webhooks/3207b9cc-6140-4d2e-bc4e-4bfb64e323e5" with the server; options: {qorus_app_connection: "tsrest-github", repo: "ondewo-", owner: "davidnich"}) (arg: {name: "INTERNAL-ERROR", statusCode: null, isOperational: True})
``` 

the value used was `ondewo-`

correcting it again resulted in: `options: {qorus_app_connection: "tsrest-github", repo: "ondewo-bp", owner: "davidnich"}` - not sure what's happening

**Comment by Foxhoundn** [comment]
This should be now fixed.

There are no more debounces when setting values, instead the throttling has been moved to the actual `getOptions` calls which are not critical for data validity.

Please not that there will always be a state where the Publish button should be disabled because we know validate on the server and we should not let the user post invalid data, only to get an error message back, that would not be a nice user experience.
