### ISSUE TITLE
Slack actions crash the page

### ISSUE THREAD

**Issue by nickmazurenko** [qoretechnologies/qorus-ide#45]
### Issue Summary

Slack actions crash the page on opening.

### Steps to Reproduce

- Create a Qog with `Request Action in A Channel` action from slack.
- Open the action step.

### Error

```
TypeError: Cannot read properties of null (reading 'length')
    at useChildren (http://localhost:3005/static/js/bundle.js:383128:37)
    at Children (http://localhost:3005/static/js/bundle.js:383491:160)
    at renderWithHooks (http://localhost:3005/static/js/bundle.js:284686:22)
    at updateFunctionComponent (http://localhost:3005/static/js/bundle.js:287886:24)
    at beginWork (http://localhost:3005/static/js/bundle.js:289833:20)
    at beginWork$1 (http://localhost:3005/static/js/bundle.js:295581:18)
    at performUnitOfWork (http://localhost:3005/static/js/bundle.js:294739:16)
    at workLoopSync (http://localhost:3005/static/js/bundle.js:294652:9)
    at renderRootSync (http://localhost:3005/static/js/bundle.js:294621:11)
    at recoverFromConcurrentError (http://localhost:3005/static/js/bundle.js:294029:24)
 ```

**Comment by davidnich** [comment]
now working
