### ISSUE TITLE
Notion Append To page Action crashes the page

### ISSUE THREAD

**Issue by nickmazurenko** [qoretechnologies/qorus-ide#46]
### Issue Summary

Notion action `Append To page` crashes the page.

### Steps to Reproduce

- Create a Qog with `Append To page Action` action from Notion.
- Open the action step.

### Error

```
TypeError: Cannot read properties of null (reading 'length')
    at fn (https://hq.qoretechnologies.com:8092/ide/static/js/bundle.js:2:3820064)
    at Rn (https://hq.qoretechnologies.com:8092/ide/static/js/bundle.js:2:3825878)
    at zo (https://hq.qoretechnologies.com:8092/ide/static/js/bundle.js:2:2519215)
    at Mu (https://hq.qoretechnologies.com:8092/ide/static/js/bundle.js:2:2530903)
    at Dl (https://hq.qoretechnologies.com:8092/ide/static/js/bundle.js:2:2577338)
    at bc (https://hq.qoretechnologies.com:8092/ide/static/js/bundle.js:2:2565391)
    at mc (https://hq.qoretechnologies.com:8092/ide/static/js/bundle.js:2:2565319)
    at gc (https://hq.qoretechnologies.com:8092/ide/static/js/bundle.js:2:2565182)
    at ic (https://hq.qoretechnologies.com:8092/ide/static/js/bundle.js:2:2561962)
    at lc (https://hq.qoretechnologies.com:8092/ide/static/js/bundle.js:2:2562353)
    at Na (https://hq.qoretechnologies.com:8092/ide/static/js/bundle.js:2:2502936)
    at https://hq.qoretechnologies.com:8092/ide/static/js/bundle.js:2:2568776
    at wc (https://hq.qoretechnologies.com:8092/ide/static/js/bundle.js:2:2568781)
    at ac (https://hq.qoretechnologies.com:8092/ide/static/js/bundle.js:2:2561239)
    at C (https://hq.qoretechnologies.com:8092/ide/static/js/bundle.js:2:3760096)
    at MessagePort.R (https://hq.qoretechnologies.com:8092/ide/static/js/bundle.js:2:3760630)
 ```

**Comment by davidnich** [comment]
now working
