### ISSUE TITLE
Asana Create A Task action crashes the page

### ISSUE THREAD

**Issue by nickmazurenko** [qoretechnologies/qorus-ide#47]
### Issue Summary

Asana `Create a Task` action crashes the page

### Steps to Reproduce

- Create a Qog with `Create a Task` action from Asana.
- Open the action step.

### Error

```
TypeError: s.map is not a function
    at https://hq.qoretechnologies.com:8092/ide/static/js/bundle.js:2:4831400
    at Object.useMemo (https://hq.qoretechnologies.com:8092/ide/static/js/bundle.js:2:2525583)
    at t.useMemo (https://hq.qoretechnologies.com:8092/ide/static/js/bundle.js:2:3747106)
    at https://hq.qoretechnologies.com:8092/ide/static/js/bundle.js:2:4831378
    at zo (https://hq.qoretechnologies.com:8092/ide/static/js/bundle.js:2:2519215)
    at Dl (https://hq.qoretechnologies.com:8092/ide/static/js/bundle.js:2:2576455)
    at bc (https://hq.qoretechnologies.com:8092/ide/static/js/bundle.js:2:2565391)
    at mc (https://hq.qoretechnologies.com:8092/ide/static/js/bundle.js:2:2565319)
    at gc (https://hq.qoretechnologies.com:8092/ide/static/js/bundle.js:2:2565182)
    at ic (https://hq.qoretechnologies.com:8092/ide/static/js/bundle.js:2:2561962)
    at ac (https://hq.qoretechnologies.com:8092/ide/static/js/bundle.js:2:2560513)
    at C (https://hq.qoretechnologies.com:8092/ide/static/js/bundle.js:2:3760096)
    at MessagePort.R (https://hq.qoretechnologies.com:8092/ide/static/js/bundle.js:2:3760630)
 ```

**Comment by davidnich** [comment]
now working
